openapi: "3.0.0"
info:
  version: 1.0.0
  title: Chatbot Cardgame
paths:
  /:
    get:
      summary: Returns a hello world message
      responses:
        '200':
          description: OK
  /chatbot:
    post:
      summary: kakaotalk chatbot api 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userRequest:
                  type: object
                  properties:
                    user:
                      type: object
                      properties:
                        id:
                          type: string
                          description: The ID of the user
                          example: 'swagger tester'
                    utterance:
                      type: string
                      description: The message spoken or written by the user
                      example: 'test message'
              required:
                - userRequest
      responses:
        '200':
          description: OK
